const genTestClass = (apexClassName, apex = "// test apex class") => {
  let testApex = `
  @isTest
  private class ${apexClassName}Test {
    /**
     * 
     * @author: 
     * @since: 
     * @description: Test Apex for ${apexClassName}. Test Apex code generated by mind-apex-test-generator
     * 
    */
`;

  const allFunc = [];
  // TODO: Regex will not work. Get Apex from tooling API symbols (or some other way to get content of method)
  const regxFunc = new RegExp(
    "(?:(?:public)|(?:private)|(?:static)|(?:protected)\\s+)*",
    "gm"
  );
  let x;
  while ((x = regxFunc.exec(apex)) !== null) {
    if (x.index === regxFunc.lastIndex) {
      regxFunc.lastIndex++;
    }
    x.forEach((match, groupIndex) => {
      console.debug(`Found match, group ${groupIndex}: ${match}`);
    });
  }
  return `
  ${testApex}
  }`;
};

module.exports = {
  genTestClass,
};
