const genTestClass = (testClass, apex = "// test apex class") => {
  const fileSepIndex =
    testClass.lastIndexOf(`\\`) || testClass.lastIndexOf(`/`);
  let testApex = `
  @isTest
  private class ${testClass.substr(fileSepIndex + 1)} {
    @isTest
      // Test Apex code generated by mind-apex-test-generator
    }
`;
  return testApex;
};

module.exports = {
  genTestClass,
};
